name: 🐛 Bug Report
description: Report a bug in the project
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: input
    id: function
    attributes:
      label: Affected Area
      description: Which module, target, or feature is exhibiting the bug?
      placeholder: "e.g., core::add() or api bindings"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "I expected the function to return..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, it returned..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal Reproduction
      description: Provide minimal C++ (or Python test) code that reproduces the issue
      placeholder: |
        ```cpp
        #include "project/header.hpp"
        
        int main() {
            // Code that reproduces the bug
            return 0;
        }
        ```
      render: cpp
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      value: |
        - OS:
        - Compiler:
        - CMake Version:
        - Language Runtime Version (if applicable):
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (error messages, logs, etc.)
    validations:
      required: false
